version: "3.7"
services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: [ "api" ]
    ports:
    - "3000:80"
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      FIREBASE_SECRETS: ${secrets.FIRE_BASE_SECRETS}
    ports:
    - "8080:8080"